### PR TITLE
Custom popover 

### PR DESCRIPTION
**Pull request by JEuler**
https://summernote.org/deep-dive/#customization support of popover customization

### CODE REVIEW

**Comment by chandrabezzo** [comment]
Hi @JEuler in another pull request you have been added returnContent, but in this pull request you don't add the returnContent. You want to discard returnContent? Please add the documentation how to use popover at Readme.md and give link for more information that can redirect to summernote describe about popover. Thank You for your support.

**Comment by JEuler** [comment]
Hi! It is just different functionality, so, I've decided to create separate PR for the returnContent and this thing.

**Comment by JEuler** [comment]
I have updated the Readme

**Comment by JEuler** [comment]
Any news? :)

**Comment by JEuler** [comment]
Are you okay?

**Pull request merged**
