### PR TITLE
iOS fix for null text

### PR DESCRIPTION
**Pull request by JEuler**
https://github.com/xrb21/flutter-html-editor/issues/19 - here is the description of the issue.

### CODE REVIEW

**Comment by chandrabezzo** [comment]
Hi @JEuler please add documentation about how to use and function returnContent at Readme.md?

**Comment by JEuler** [comment]
Okay, will do at weekend

**Comment by JEuler** [comment]
Added. Or you want an example? It is just allows to use textContent from await keyEditor.currentState.getText(). The await keyEditor.currentState.getText() is not working on iOS.

**Comment by JEuler** [comment]
Any news? 👍

**Comment by Bruner4** [comment]
Hi @JEuler , could you provide an example for the returnContent in iOS?
In Android I used to get the text outside the FlutterSummernote widget, but now I see I have to get it inside the widget through the returnContent, is it right?

**Comment by JEuler** [comment]
Hi!

```dart
 returnContent: (content) {
                  _doSomethingWithText(content);
 }    
```               

Now you need to call `keyEditor.currentState.getText()` and whoala, you are firing `returnContent` and all is working for both platforms.

**Pull request merged**
