### PR TITLE
ios sizing fix

### PR DESCRIPTION
**Pull request by JEuler**
I was getting the very tiny iOS viewport without this meta.

### CODE REVIEW

**Comment by chandrabezzo** [comment]
Hi @JEuler I was reviewed your files changed, but I think you not only resolve about ios sizing fix. Can you give more information what do you want to add or resolve with this resolve? thank you.

**Comment by JEuler** [comment]
Oh, sorry, I also have a glitch on iOS with the `getText` is returning null the first time. I've added it here, which is wrong. 

Basically, I have added `returnContent` function and set up the timeouts. Now the iOS version of editor is working nice for me. I can separate the sizing fix and `getText` fix. Or I can rename the PR. :)

**Comment by chandrabezzo** [comment]
Maybe you need add check Platform.isIOS() to make sure the condition in iphone. If you found this error in iOS and have not any issue in Android please use specific platform, so your code not make package unstable because we are focused on both platform not only support one platform. Thank you.

**Comment by JEuler** [comment]
Okay, I will rework this PR later then.

**Comment by chandrabezzo** [comment]
Thank you very much @JEuler for your support for this package. I will waiting your PR again.

**Pull request closed without merging**
